sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- sudo apt-get update
- sudo add-apt-repository "deb http://sdkrepo.atlassian.com/debian/ stable contrib"
- sudo cat < /etc/apt/sources.list
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B07804338C015B73
- sudo apt-get update
- sudo sudo apt-get install atlassian-plugin-sdk
install: true
script:
- atlas-package
- mv target/testfairy-jira-p2-plugin-*SERVER.jar target/testfairy-jira-p2-plugin.jar
deploy:
  provider: releases
  api_key:
    secure: HDG4U7mi6i1WLu/IDd7PwWtWxh5snRnm5PyoN8K8i1omzWciaDrIHblvOETmbXCq60hWYJQzeF6ow7ck0tj3ASflI0S0KDGB7lEuAOPChBs7X8lD3NMdPHF3qXrTDIbQp00yOgGzcUeLy7it1QcY2iiSvKQ0rPhbkXqX5CqChTYcadWXSO0F4BEIMPG95neIHdqmIXE9r2SQ50EvO9Eyqc4sGfjJBq+w/Hr1x+ucQTanP8krf0Zjtmn90fHK7UXt5qxcSdRJ5azwp7SPcf2IxWvJB7L48C1ktQcjt9uWMZ3hJjuqNcU1LhG71GtTy7YAreMM1U16pG4T5b3xJ16k43UoPJQJYwGqPDHeaNtAap77pWkFj2/t9pd/aaVu69YkoExc2L0Srhobk0s3yQAxUEJa4xwYqZPFaXsS6pIV3769/i+Gfjec2VA8QGEWZ5lcoZPO5l1iDEtOvTvsYGoF8AsqCWs0DbKrYv824rfR2mfOgt/xpt+1bY+GvI0whuCY9TSyUWZSa+cwHHh53bmSOKBAMa0T1cPdu9vdO1oAN+7RnbaixZFa1Ro3mKUX9LyVAZJEa9YoaFbjuabBknPCvHn+WHBGB/H+w/KZ6emCfjbknyO4wSruf/tsN3ZNA5ZcDa0RrghWQux5rEQ4XlpuG6Hv4PtMSwuiyQKy9tIv32A=
  file: target/testfairy-jira-p2-plugin.jar
  on:
    tags: true
    repo: testfairy/testfairy-jira-p2-plugin
notifications:
  email: true
